# Generated by Django 5.0.2 on 2025-02-15 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = []
