# Generated by Django 5.0.2 on 2025-02-15 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_auto_20250215_2032"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advertiserprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Advertiser Profile",
                "verbose_name_plural": "Advertiser Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="collaboration",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="influencerprofile",
            options={
                "ordering": ["-follower_count", "-created_at"],
                "verbose_name": "Influencer Profile",
                "verbose_name_plural": "Influencer Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_review_project", "Can review project"),
                    ("can_manage_project", "Can manage project"),
                ],
            },
        ),
        migrations.RemoveField(
            model_name="advertiserprofile",
            name="bio",
        ),
        migrations.AddField(
            model_name="advertiserprofile",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Tell us about your company and what kind of influencers you're looking for",
            ),
        ),
        migrations.AddField(
            model_name="advertiserprofile",
            name="industry",
            field=models.CharField(
                choices=[
                    ("Fashion", "Fashion & Apparel"),
                    ("Beauty", "Beauty & Cosmetics"),
                    ("Technology", "Technology & Software"),
                    ("Food", "Food & Beverage"),
                    ("Health", "Health & Wellness"),
                    ("Travel", "Travel & Tourism"),
                    ("Education", "Education & E-learning"),
                    ("Finance", "Finance & Fintech"),
                    ("Entertainment", "Entertainment & Media"),
                    ("Retail", "Retail & E-commerce"),
                    ("Other", "Other"),
                ],
                default="Other",
                help_text="Primary industry of your business",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="proposal",
            field=models.TextField(
                blank=True, default="", help_text="Your proposal for this project"
            ),
        ),
        migrations.AddField(
            model_name="influencerprofile",
            name="engagement_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Average engagement rate (likes + comments) / followers * 100",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="influencerprofile",
            name="platform",
            field=models.CharField(
                choices=[
                    ("Instagram", "Instagram"),
                    ("TikTok", "TikTok"),
                    ("YouTube", "YouTube"),
                    ("Multiple", "Multiple Platforms"),
                ],
                default="Multiple",
                help_text="Your main social media platform",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="advertiserprofile",
            name="company_name",
            field=models.CharField(
                help_text="Name of your company or brand", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="advertiserprofile",
            name="website",
            field=models.URLField(blank=True, help_text="Your company website URL"),
        ),
        migrations.AlterField(
            model_name="collaboration",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="influencerprofile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Tell us about yourself and your content creation experience",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="influencerprofile",
            name="follower_count",
            field=models.PositiveIntegerField(
                help_text="Total number of followers on your main platform"
            ),
        ),
        migrations.AlterField(
            model_name="influencerprofile",
            name="instagram_handle",
            field=models.CharField(
                blank=True,
                help_text="Your Instagram username (start with @)",
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Instagram handle must start with @ and contain only letters, numbers, dots and underscores",
                        regex="^@[a-zA-Z0-9._]{1,30}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="influencerprofile",
            name="niche",
            field=models.CharField(
                choices=[
                    ("Fashion", "Fashion"),
                    ("Beauty", "Beauty"),
                    ("Technology", "Technology"),
                    ("Gaming", "Gaming"),
                    ("Lifestyle", "Lifestyle"),
                    ("Food", "Food"),
                    ("Travel", "Travel"),
                    ("Fitness", "Fitness"),
                    ("Education", "Education"),
                    ("Business", "Business"),
                    ("Entertainment", "Entertainment"),
                    ("Other", "Other"),
                ],
                help_text="Your primary content category",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="influencerprofile",
            name="tiktok_handle",
            field=models.CharField(
                blank=True,
                help_text="Your TikTok username (start with @)",
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="TikTok handle must start with @ and contain only letters, numbers, dots and underscores",
                        regex="^@[a-zA-Z0-9._]{1,30}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="influencerprofile",
            name="youtube_channel",
            field=models.URLField(
                blank=True, help_text="Your YouTube channel URL", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="budget",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Project budget in USD",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="deadline",
            field=models.DateField(help_text="Project completion deadline"),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                help_text="Detailed description of the project and its goals"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="requirements",
            field=models.TextField(
                help_text="Specific requirements and expectations for the influencer"
            ),
        ),
    ]
