# Generated by Django 5.0.2 on 2025-02-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_collaboration_options_projectupdate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectupdate",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="projectupdate",
            name="attachment_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="projectupdate",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="projectupdate",
            name="update_type",
            field=models.CharField(
                choices=[
                    ("BRIEF", "Brief"),
                    ("PROGRESS", "Progress Update"),
                    ("REVISION", "Revision Request"),
                    ("FEEDBACK", "Feedback"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="projectupdate",
            index=models.Index(
                fields=["collaboration", "-created_at"],
                name="core_projec_collabo_3cba15_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectupdate",
            index=models.Index(
                fields=["sender", "-created_at"], name="core_projec_sender__91c2ed_idx"
            ),
        ),
    ]
